### ISSUE TITLE
ASI for Patch 7/8 disables corona effects

### ISSUE THREAD

**Issue by Thundersmacker** [Parallellines0451/GTAIV.ShaderFixesCollection#11]
Using the v200 shader fixes with the standalone ASI for patch 7/8 disables the corona effects on vehicles completely.

**Comment by inhumanesmoke** [comment]
I'm having the same issue and noticed more.  Certain lights aren't functioning at all like the L-train headlights except for the other trains passing by.  Also the police lights don't look correct.

**Comment by TabbyEgg** [comment]
this happens on main installation as well, luis safehouse has messed up lighting and lamp is refusing to properly show and the far away smooth filter is awful

**Comment by Parallellines0451** [comment]
Use FusionFix instead of the asi. It's available on pre-CE versions as well.
