### ISSUE TITLE
Lighting issues (1.0.7.0 Main Install V200)

### ISSUE THREAD

**Issue by TabbyEgg** [Parallellines0451/GTAIV.ShaderFixesCollection#12]
Police car refuses to light up properly, vehicles have missing corona effect, Luis's safehouse has messed up lightning including the outside lamp. underground train station has no lighting at ALL unless you come close to one.

I installed the version V200 via file replacing and not the ASI and it's on 1.0.7.0 

![image](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/132162694/f38b3036-5982-417f-ba03-103ad9ffc7aa)
![image](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/132162694/c39e4d57-2a63-412a-8ad8-2263476c7754)
![image](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/132162694/1a21a94c-805c-40cd-8629-5ab5359888e8)
![image](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/132162694/0758d355-01a5-4172-b65b-635f2abd1067)

**Comment by Parallellines0451** [comment]
Either the .asi or FusionFix are required for the shaders to work.
