### ISSUE TITLE
Bug shadows

### ISSUE THREAD

**Issue by AndiDink00x** [Parallellines0451/GTAIV.ShaderFixesCollection#2]
One of many bugs i have found is that some shadow casting is missing while on some occasions are displayed correctly

https://imgur.com/a/ofCo0VI
https://imgur.com/a/2V8QOrj
https://imgur.com/a/QkGNgRJ

**Comment by Parallellines0451** [comment]
Not a bug in the shaders. Cars don't cast shadows from dynamic lights on PC because Rockstar purposefully disabled them for their stencil value. This can't be fixed through shaders only and needs code injection.

**Comment by MehranAkbarii** [comment]
I hate ZolikhaPatch developer so much , he think who he is , he didn't and don't want to make his mod compatible with latest CE  version from steam, he even didnt make his project open source for other devs to make a compatible version of his mod for latest CE you know why ? I guess becuase his mod is spyware and he can access your PC when you connecting to online servers and playing the game MP mode also he published a garbage downgrader which that ruin your game data and you have to do a lot of boring tasks to make your game workable as before newer fusion fix versions will not work after downgrading to version 1.0.8.0 and you have to use out dated versions and for trying latest fixes on 1.0.8.0 and below you have to do so much extra tasks and maybe new fixes not working after all and also downgrading make your game depended to Xlive as before 2020 CE 
and you have to use annoying workarounds like xliveless to get rid of that sh*t I prefer that play without dynamic shadows to using version 1.0.8.0 I hope some one in future could re-enable dynamic shadows same as ZolikhaPatch developer.

**Comment by MehranAkbarii** [comment]
I hate ZolikhaPatch developer so much , he think who he is , he didn't and don't want to make his mod compatible with latest CE version from steam, he even didn't make his project open source for other devs to make a compatible version of his mod for latest CE you know why ? I guess becuase his mod is spyware and he can access your PC when you connecting to online servers and playing the game MP mode also he published a garbage downgrader which that ruin your game data and you have to do a lot of boring tasks to make your game workable as before newer fusion fix versions will not work after downgrading to version 1.0.8.0 and you have to use out dated versions and for trying latest fixes on 1.0.8.0 and below you have to do so much extra tasks and maybe new fixes not working after all and also downgrading make your game depended to Xlive as before 2020 CE and you have to use annoying workarounds like xliveles to get rid of that sh*t I prefer that play without dynamic shadows to using version 1.0.8.0 I hope some one in future could re-enable dynamic shadows same as ZolikhaPatch developer.
