### ISSUE TITLE
Console gamma - default turn on

### ISSUE THREAD

**Issue by tolo171uk** [Parallellines0451/GTAIV.ShaderFixesCollection#4]
Hi. Could you include 2nd shaders folder with console gamma turned on in future updates please? (Current pack V109 contains console gamma turn off by default).
Fusion Fix contains option to turn on Console Gamma however some people can use downgraded version of GTA IV (example 1.0.8.0) or mods like Actual Complete Version which new Fusion Fix is not compatible. Thank you.

**Comment by spidergrear2** [comment]
FusionFix got a backport by Zolika recently get it [here](https://mega.nz/file/2ZB1WbbC#ZqG5X8k48zsvkNshWHnS5_EX78KEDz5V9y54X5CupFg)

**Comment by tolo171uk** [comment]
Hi @spidergrear2 . Thank you for link. I have test it and it works only with original GTA IV. When I try to load one of the DLC (TLAD or TBOGT) screen stucks on 'Loading'. I am using The Actual Complete Edition mod.
Like I mentioned on previous post, it will be really great if 2nd folder with Console Gamma turned on can be included to avoid issue. Or if Console Gamma can be turned on by default. It can resolve issue for people who are using mods like The Actual Complete Edition or any other and would like to play DLC's.

**Comment by HEKJJBVCG** [comment]
> FusionFix got a backport to 1070 & 1080 by Zolika recently get it [here](https://mega.nz/file/2ZB1WbbC#ZqG5X8k48zsvkNshWHnS5_EX78KEDz5V9y54X5CupFg)

New link? Its not working

**Comment by tolo171uk** [comment]
https://mega.nz/file/mUwQGZ6D#D3ZrfuEmpnBvTCPV8qoh8GNgc40To8j0I5IKZNHmQ1A

**Comment by Parallellines0451** [comment]
I'll include that optional shader in the next release. In the meantime you can toggle the gamma in rage_postfxPS12, 14, 16, 18, 24, 26 and 28
Search for "console gamma" and change 0, 0, 88, 89 to 1, 0, 88, 99 in those seven files
